### ISSUE TITLE
CookieJar Option

### ISSUE THREAD

**Issue by yiming1995** [bogdanfinn/tls-client#1]
Excuse me, there is no cookiejar option for tls-client?

**Comment by bogdanfinn** [comment]
@yiming1995 not exactly sure why you need to define a separate cookiejar. a default cookie jar will be used in the http client and you can set / get cookies by calling `GetCookies` or `SetCookies` on the client.

Nevertheless i added the option in v0.2.1 to define a custom cookiejar. You just have to implement the `http.CookieJar` interface. The client interface was also extended to have a function to get the cookiejar from the client: `GetCookieJar() http.CookieJar`
