### ISSUE TITLE
Error when running example code: tls: error decoding message[Bug]: 

### ISSUE THREAD

**Issue by phoenix6111** [bogdanfinn/tls-client#111]
### TLS client version

v1.3

### System information

Win10 system version

### Issue description

Hello,
I was trying to run the example code provided in the repository for the tls-client at index_custom_client.js (link: [index_custom_client.js](https://github.com/bogdanfinn/tls-client/blob/master/cffi_dist/example_node/index_custom_client.js)). However, I encountered an error when attempting to make a request to "https://microsoft.com". The error message is:
"failed to do request: Get "https://microsoft.com": remote error: tls: error decoding message"

Could you please help me understand what might be causing this issue and how to resolve it? Any guidance or updates to the code that might help resolve this error would be greatly appreciated.
Thank you for your assistance.

### Steps to reproduce / Code Sample

failed to do request: Get "https://microsoft.com": remote error: tls: error decoding message. like this:
![微信图片_20240426162633](https://github.com/bogdanfinn/tls-client/assets/9884856/65f720b3-6c75-4edd-aa0f-06ee50c0cccc)

**Comment by bogdanfinn** [comment]
@phoenix6111 
i forgot to update the examples. 
in the last couple updates we introduced some more flexibility for the custom client options ... that means on the other hand some values need to be explicit defined.

So for chrome custom client (and for the provided examples to work) you need to define in addition the following custom client values:

```
"alpnProtocols": ["h2", "http/1.1"],
"alpsProtocols": ["h2"],
```

next to for example `supportedVersions`

I will update the examples in the next commit.

**Comment by phoenix6111** [comment]
I got it, thank you very much for your help!
