### ISSUE TITLE
[Feature Request]: Extension encrypted_client_hello

### ISSUE THREAD

**Issue by thaiduongme** [bogdanfinn/tls-client#116]
### Describe the feature / enhancement and how it would improve things

Can you add the encrypted_client_hello extension feature? I'm facing an issue that requires this, but I have no idea how to build that custom feature.

### Describe how your proposal will work, with code and/or pseudo-code

The encrypted_client_hello (ECH) extension is a feature that encrypts the ClientHello message in TLS (Transport Layer Security) to enhance privacy by hiding the details of the handshake. Implementing this feature involves modifying the TLS handshake process to include ECH.

**Comment by bogdanfinn** [comment]
@thaiduongme did you try out built in profile of chrom124? This has ECH added.
