### ISSUE TITLE
[Documentation Request]: Set GREASE Cipher by CFFI

### ISSUE THREAD

**Issue by fakeastap** [bogdanfinn/tls-client#118]
### Describe the feature / enhancement and how it would improve things

Hello. Is there any possibility to set GREASE Cipher using your library via CFFI from Python?

I see that this is very easy to do in Go, but can I implement it in Python?

I will attach a screenshot for clarity. I was able to fake Client Hello completely, except for this cipher.

And in general, does the absence of this cipher affect my trust? After all, ja3 hash is identical anyway. Thanks in advance.
![image](https://github.com/bogdanfinn/tls-client/assets/26527039/58f6514d-ab51-4b82-a370-6a35362e2336)
![image](https://github.com/bogdanfinn/tls-client/assets/26527039/661da8b3-5aa4-4c43-b233-7ff968ede9e6)

### Describe how your proposal will work, with code and/or pseudo-code

None

**Comment by bogdanfinn** [comment]
@fakeastap just add `2570` to the ja3_string at the exact place where you want to GREASE Cipher to appear. So in your case directly after `771,2570-4865-4866-4867-....` 

`2570` is the magic placeholder number for GREASE. I think i just mist to document it in the official docs.
