### ISSUE TITLE
[Feature Request]: Ability to send complex JSON object in POST request body

### ISSUE THREAD

**Issue by ndywicki** [bogdanfinn/tls-client#122]
### Describe the feature / enhancement and how it would improve things

I'm using a Typescript wrapper implementation of `tls-client` like https://www.npmjs.com/package/node-tls-client, 
But It's not possible to send a JSON payload in the HTTP `POST`body  with nested object:

````
const response = await session.post(apiUrl, {
        headers: headers,
        cookies: cookies,
        body: {
          param1: 1234,
          param2: { param3: "test"}
        },
      })
````

Issue:
`"body":"json: cannot unmarshal object into Go struct field RequestInput.requestBody of type string`

Thank you.

### Describe how your proposal will work, with code and/or pseudo-code

It's ok if I flatten the object, but the request is not understood by the remote API server.

**Comment by KannaAny** [comment]
Convert the nested object to a JSON string

`JSON.stringify({
  param1: 1234,
  param2: { param3: "test" }
})`

**Comment by ndywicki** [comment]
Ok, I thought I had already tested the stringify .. but in doubt I did another test and it works! Probably with another tls client JS libs or fatigue 😄 

I close the request.
