### ISSUE TITLE
[Bug]: Missing Specific File (tls-client-linux-ubuntu-amd64-1.7.6.so) in Latest Release

### ISSUE THREAD

**Issue by shubhamshah02** [bogdanfinn/tls-client#124]
### TLS client version

v1.7.6

### System information

Linux/Ubuntu on Heroku

### Issue description

tls-client-linux-ubuntu-amd64-1.7.6.so is missing from the newest release which breaks the noble_tls library that I use for asynchronous TLS.

### Steps to reproduce / Code Sample

Starting a project with noble_tls will try to pull the .so file from the latest release of tls-client but since the tls-client-linux-ubuntu-amd64-1.7.6.so file is missing, it's crashing my script immediately. It used to work fine with 1.7.5 on tls-client because that file was there.

**Comment by bogdanfinn** [comment]
@shubhamshah02 my bad. added the files here: https://github.com/bogdanfinn/tls-client/releases/tag/v1.7.6
