### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by LyonSquad** [bogdanfinn/tls-client#133]
### Describe the feature / enhancement and how it would improve things

@bogdanfinn  hello sir would you compile this and release a windows executable file .exe for windows 10/11
YOu release a DLL file for windows , i tried rename the .dll to .exe it doesn't work

### Describe how your proposal will work, with code and/or pseudo-code

@bogdanfinn  hello sir would you compile this and release a windows executable file .exe for windows 10/11
YOu release a DLL file for windows , i tried rename the .dll to .exe it doesn't work

**Comment by univexnet** [comment]
This is a library, to use it as a standalone app, use the tls-client-api, which has .exe build available. It is available here; [tls-client-api](https://github.com/bogdanfinn/tls-client-api/releases/tag/v1.7.8)

**Comment by bogdanfinn** [comment]
@LyonSquad please stop spamming the issues with your personal requests. this is not what they are meant to be.
