### ISSUE TITLE
What is the license of this software?

### ISSUE THREAD

**Issue by dreirund** [bogdanfinn/tls-client#24]
What is the license of this software?

I could not find a `LICENSE`, `COPYING` or similar file.

I want to write an Arch linux package for this, and so I need to know the licensing terms.

Regards!

**Comment by bogdanfinn** [comment]
@dreirund i will add one in the future... but in general i would say "do whatever you want with my work just do not sue me" :-D Will include a LICENSE file in the next update

**Comment by dreirund** [comment]
> i will add one in the future... but in general i would say "do whatever you want with my work just do not sue me" :-D Will include a LICENSE file in the next update

I have now mentioned as licensing information what you have stated, see [&nearr;&hairsp;here](https://aur.archlinux.org/pkgbase/tls-client-git).

**Comment by bogdanfinn** [comment]
Added a LICENSE in the last release.
