### ISSUE TITLE
invalid response cookies

### ISSUE THREAD

**Issue by erg43hergeg** [bogdanfinn/tls-client#30]
Any chance of adding a flag or something to disable the messages? they are redundant anyway because, apart from the message, the value is immediately sanitized and passed on. this happens on google and youtube - related to https://github.com/bogdanfinn/tls-client/issues/23
![2023-03-16_00-54_1](https://user-images.githubusercontent.com/101474087/225469857-bf5cfe30-6042-4448-abf6-cc66666ae523.png)

**Comment by erg43hergeg** [comment]
https://github.com/Carcraftz/fhttp/commit/bd427df5ca71127d2c167131e61e3ea3cfc1bd4b

**Comment by bogdanfinn** [comment]
@erg43hergeg should be implemented in [b707dce](https://github.com/bogdanfinn/tls-client/commit/b707dce87e9fc883a76e04e570d3047278e0245e)
