### ISSUE TITLE
[Feature request] split out prebuilt binaries from this repository to some external "blob storage".

### ISSUE THREAD

**Issue by dreirund** [bogdanfinn/tls-client#31]
Suggestion:

Split source code repository and distribution of prebuilt library binaries.

So that a repository clone is smaller, and users are not confused whether prebuilt binaries are always up to date with souce code.

Having large binaries in version control also is not a good idea.

And prebuilt binaries are available via separate download URL.

Regards!

**Comment by bogdanfinn** [comment]
@dreirund i removed the prebuilt binaries and placed them directly into the new official (wip) documentation:
https://bogdanfinn.gitbook.io/open-source-oasis/shared-library/downloads

https://bogdanfinn.gitbook.io/open-source-oasis/standalone-api-application/download

Just let me know if this is enough for you or you need them hosted somewhere else?

**Comment by bogdanfinn** [comment]
@dreirund gitbook somehow does not allow hosting executable files.

from now on i will add the prebuilt binaries to releases here in github: https://github.com/bogdanfinn/tls-client/releases
