### ISSUE TITLE
[FEATURE REQUEST] Support arm32

### ISSUE THREAD

**Issue by BlueSchnabeltier** [bogdanfinn/tls-client#45]
.

**Comment by bogdanfinn** [comment]
> rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang rpi gang

what does this mean?

**Comment by BlueSchnabeltier** [comment]
I mean the Raspberry Pi which is an arm computer with a small form factor often used for servers. It would be optimal if you would make tls-client for arm32 so this project is more acessible for projects that need this as a proxy to circumvent antiscraping measures.

**Comment by LovanDog** [comment]
still no support?

**Comment by bogdanfinn** [comment]
With the current build approach it is not possible to me to cross compile.

```sh
➜ GOOS=linux CGO_ENABLED=1 GOARCH=arm32 CC="arm-unknown-linux-gnueabi-gcc" go build -buildmode=c-shared -o ./dist/tls-client-linux-arm32.so  
-buildmode=c-shared not supported on linux/arm32

```

I will try out the `xgo` build tool in the next release to create the libraries for linux/arm. Please double check them then :-)

**Comment by bogdanfinn** [comment]
@BlueSchnabeltier @LovanDog can you please check out the following shared libraries here: https://github.com/bogdanfinn/tls-client/releases/tag/v1.5.0

please look for your required von starting with the name `tls-client-xgo-*`
