### ISSUE TITLE
carrying forward task jar handling from fhttp

### ISSUE THREAD

**Issue by sukhdev96** [bogdanfinn/tls-client#49]
there seems to be no way to call httpclient.CookieJar object in this client despite the older fhttp code allowed for this. can you possibly reintroduce it or add a way to share cookie jars between clients?

**Comment by bogdanfinn** [comment]
@sukhdev96 just added a `GetCookieJar()` function to the client.
https://github.com/bogdanfinn/tls-client/commit/7d5166e0e444d63d131b35aba8abf76e2d5b3164
