### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by imblowsnow** [bogdanfinn/tls-client#57]
### TLS client version

v1.4.0

### System information

windiows 10

### Issue description

when i use streamOutputPath options

### Steps to reproduce / Code Sample

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff936f0fcb4]

goroutine 17 [running, locked to thread]:
github.com/bogdanfinn/tls-client/cffi_src.(*TLSClientError).Error(0x1148c31d745a6199?)
        /Users/bogdan/Development/Solem8s/tls-client/cffi_src/types.go:20 +0x14
github.com/bogdanfinn/tls-client/cffi_src.(*TLSClientError).Error(...)
        /Users/bogdan/Development/Solem8s/tls-client/cffi_src/types.go:20
main.handleErrorResponse({0xc00001c5d0, 0x24}, 0x1, 0xc00005d270)
        /Users/bogdan/Development/Solem8s/tls-client/cffi_dist/main.go:283 +0xcf
main.request(0x0?)
        /Users/bogdan/Development/Solem8s/tls-client/cffi_dist/main.go:259 +0x795

**Comment by bogdanfinn** [comment]
@imblowsnow i pushed a commit on the master branch adressing this issue. please let me know if it fixes the problem for you.

**Comment by imblowsnow** [comment]
Can you release a version?

**Comment by imblowsnow** [comment]
> @imblowsnow i pushed a commit on the master branch adressing this issue. please let me know if it fixes the problem for you
@bogdanfinn Can you release a version?
