### ISSUE TITLE
[Feature Request]: How to support streaming response?

### ISSUE THREAD

**Issue by a410202049** [bogdanfinn/tls-client#63]
### Describe the feature / enhancement and how it would improve things

How to support streaming response?

### Describe how your proposal will work, with code and/or pseudo-code

How to support streaming response?

**Comment by bogdanfinn** [comment]
@a410202049 maybe this helps you? 
https://github.com/bogdanfinn/tls-client/pull/21

**Comment by a410202049** [comment]
ok thank you. this is exactly what I wanted
