### ISSUE TITLE
[Feature Request]: Provide an option to set default headers (and header orders) 

### ISSUE THREAD

**Issue by 3ldar** [bogdanfinn/tls-client#68]
### Describe the feature / enhancement and how it would improve things

I didn't find the proper settings to set the headers in a client-wise fashion. (Like in C# `HttpClient`s `SetDefaultRequestHeaders`) It allows you to set headers for the client's lifetime. Setting a header in a request level will override the default headers. If it is absent it would be nice to have such a feature.

### Describe how your proposal will work, with code and/or pseudo-code

```
options := []tlsClient.HttpClientOption{
		tlsClient.WithTimeoutSeconds(30),
		tlsClient.WithClientProfile(tlsClient.MappedTLSClients[tlsIdentifier]),
		//tlsClient.WithDebug(),
		tlsClient.WithRandomTLSExtensionOrder(),
		tlsClient.WithProxyUrl(proxy),
		tlsClient.WithNotFollowRedirects(),
		tlsClient.WithInsecureSkipVerify(),
		tlsClient.WithCookieJar(jar),
		tlsClient.WithCatchPanics(),
                tlsClient.WithDefaultHeaders(someHeadersHere), // <--
	}
```

**Comment by bogdanfinn** [comment]
Introduced in version v1.6.0
