### ISSUE TITLE
[Bug]: Running a python script that imports tls-client causes error

### ISSUE THREAD

**Issue by Dashbloxx** [bogdanfinn/tls-client#72]
### TLS client version

v0.2.1

### System information

Raspbian (Debian GNU/Linux)
BCM2835 (4) @ 1.800GHz

### Issue description

Each time I attempt to run a python script that imports tls-client, I get this error:

OSError: /home/matthew/.local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-arm64.so: cannot open shared object file: No such file or directory

### Steps to reproduce / Code Sample

Install tls-client package from pip3
Make a new python script in a Raspbian environment
Import tls-client
Run the python script

**Comment by bogdanfinn** [comment]
@Dashbloxx i think this issue belongs to the following repository: https://github.com/FlorianREGAZ/Python-Tls-Client
