### ISSUE TITLE
[Bug]: zoominfo网站请求不通

### ISSUE THREAD

**Issue by huangpd** [bogdanfinn/tls-client#73]
### TLS client version

v1.3.12

### System information

url = 'https://www.zoominfo.com/c/apple-inc/2441797'
code = 403

### Issue description

url = 'https://www.zoominfo.com/c/apple-inc/2441797'
code = 403

### Steps to reproduce / Code Sample

url = 'https://www.zoominfo.com/c/apple-inc/2441797'
code = 403

**Comment by jsnjack** [comment]
works for me! maybe the client wasn't configured properly?

**Comment by bogdanfinn** [comment]
same for me.
