### ISSUE TITLE
[Feature Request]: chrome 118

### ISSUE THREAD

**Issue by Mouad-scriptz** [bogdanfinn/tls-client#83]
### Describe the feature / enhancement and how it would improve things

chrome 118 tls changes

### Describe how your proposal will work, with code and/or pseudo-code

chrome 118 tls changes

**Comment by bogdanfinn** [comment]
@Mouad-scriptz please take a look at the discussion here: https://github.com/refraction-networking/utls/issues/240

The ECH Extension is not implemented yet in utls.

**Comment by Mouad-scriptz** [comment]
So there has been no changes in chrome 118?

> @Mouad-scriptz please take a look at the discussion here: [refraction-networking/utls#240](https://github.com/refraction-networking/utls/issues/240)
> 
> The ECH Extension is not implemented yet in utls.

**Comment by yifeikong** [comment]
AFAIK, ECH is only enabled in chrome 119.

**Comment by RonaldinhoL** [comment]
> AFAIK, ECH is only enabled in chrome 119.

i observed extensionEncryptedClientHello (boringssl) (65037) in chrome 118 too

**Comment by bogdanfinn** [comment]
@Mouad-scriptz chrome120 is implemented in latest version 1.7.0/1.7.1
