### ISSUE TITLE
[Feature Request]: Add 0x0301, 0x0303 and other sign algoritms to shared lib.

### ISSUE THREAD

**Issue by fakeastap** [bogdanfinn/tls-client#88]
### Describe the feature / enhancement and how it would improve things

Hello. I am using your library from Python. I am trying to make a copy of Client Hello package from one mobile application. On the iOS version of the app, I have successfully captured the parameters I need and it works as I need it to.
But trying to do the same with the Android version, I am facing a problem where it is not possible to pass the required supported_signature_algorithms parameters. 

Could you please update the table of existing TLS supported_signature_algorithms or allow me to pass them in raw form as a hexadecimal number? 

![image](https://github.com/bogdanfinn/tls-client/assets/26527039/c3e6ed97-f8e0-4da9-8acb-7fd99676f237)
<img width="252" alt="image" src="https://github.com/bogdanfinn/tls-client/assets/26527039/7d83b1e6-b194-4d36-93e4-8203f625da9b">
<img width="962" alt="image" src="https://github.com/bogdanfinn/tls-client/assets/26527039/8254ede2-c550-41df-b032-6d031c190bbc">

I hope for your responsiveness. And thank you for your work.

### Describe how your proposal will work, with code and/or pseudo-code

            supported_signature_algorithms=[
                "PKCS1WithSHA512",
                "ECDSAWithP521AndSHA512",
                "PKCS1WithSHA384",
                "ECDSAWithP384AndSHA384",
                "PKCS1WithSHA256",
                "ECDSAWithP256AndSHA256",
                0x0301,  # TODO unknown
                0x0303,  # TODO unknown
                "PKCS1WithSHA1",
                "ECDSAWithSHA1",
            ]

**Comment by bogdanfinn** [comment]
@fakeastap can you try adding the following two strings to your array:

```
"769" instead of 0x0301
"771" instead of 0x0303
```

see:


I implemented back then a possibility to supply the usigned integer value as string if its not part of the mapping table.
This should do the trick for you.

But sure i will add the two values in one of the next releases.

**Comment by bogdanfinn** [comment]
https://www.simonv.fr/TypesConvert/?integers

<img width="388" alt="Bildschirmfoto 2023-12-14 um 21 34 02" src="https://github.com/bogdanfinn/tls-client/assets/17678241/a163a1ac-647b-448d-b669-7d6979194050">
<img width="367" alt="Bildschirmfoto 2023-12-14 um 21 33 51" src="https://github.com/bogdanfinn/tls-client/assets/17678241/08b59017-3970-4b30-85ec-9a7e49038aed">

**Comment by fakeastap** [comment]
oh thanks!! it works

**Comment by bogdanfinn** [comment]
@fakeastap what do you mean with "it is better to write the values in hex" ?

**Comment by fakeastap** [comment]
> @fakeastap what do you mean with "it is better to write the values in hex" ?

I meant that parameters passed as a string do not need to be converted from hexadecimal to decimal.
This works fine:
"301" instead of 0x0301
"303" instead of 0x0303.

Just a quick fix, for users who run into a similar problem.

Sorry for my English. I'm just using a translator.

**Comment by bogdanfinn** [comment]
@fakeastap added those values in latest release v.1.7.0/1.7.1
